# Generated by Django 5.1.6 on 2026-07-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('showtimes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_pagado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'asiento reservado',
                'verbose_name_plural': 'asientos reservados',
                'db_table': 'reserva_asientos',
                'ordering': ['funcion_asiento__asiento__fila', 'funcion_asiento__asiento__numero'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('expirada', 'Expirada')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expira_en', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funcion', models.ForeignKey(db_column='funcion_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='showtimes.funcion')),
            ],
            options={
                'verbose_name': 'reserva',
                'verbose_name_plural': 'reservas',
                'db_table': 'reservas',
                'ordering': ['-created_at'],
            },
        ),
    ]
