# Generated by Django 5.1.6 on 2026-07-22 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        ('showtimes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservaasiento',
            name='funcion_asiento',
            field=models.ForeignKey(db_column='funcion_asiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='reserva_asientos', to='showtimes.funcionasiento'),
        ),
        migrations.AddField(
            model_name='reservaasiento',
            name='reserva',
            field=models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='reservations.reserva'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['usuario'], name='idx_reservas_usuario'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['funcion'], name='idx_reservas_funcion'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['estado'], name='idx_reservas_estado'),
        ),
        migrations.AddConstraint(
            model_name='reservaasiento',
            constraint=models.UniqueConstraint(fields=('funcion_asiento',), name='uq_reserva_funcion_asiento'),
        ),
    ]
