# Generated by Django 5.1.6 on 2026-07-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'cine',
                'verbose_name_plural': 'cines',
                'db_table': 'cines',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo_sala', models.CharField(default='2D', max_length=20)),
                ('capacidad', models.IntegerField()),
                ('activa', models.BooleanField(default=True)),
                ('cine', models.ForeignKey(db_column='cine_id', on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='showtimes.cine')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'db_table': 'salas',
                'ordering': ['cine_id', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField()),
                ('idioma', models.CharField(blank=True, max_length=50, null=True)),
                ('subtitulos', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(db_column='pelicula_id', on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='movies.pelicula')),
                ('sala', models.ForeignKey(db_column='sala_id', on_delete=django.db.models.deletion.PROTECT, related_name='funciones', to='showtimes.sala')),
            ],
            options={
                'verbose_name': 'funcion',
                'verbose_name_plural': 'funciones',
                'db_table': 'funciones',
                'ordering': ['fecha_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila', models.CharField(max_length=2)),
                ('numero', models.IntegerField()),
                ('tipo', models.CharField(choices=[('estandar', 'Estandar'), ('vip', 'VIP'), ('discapacitado', 'Accesible')], default='estandar', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('sala', models.ForeignKey(db_column='sala_id', on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='showtimes.sala')),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'db_table': 'asientos',
                'ordering': ['fila', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='FuncionAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('reservado', 'Reservado'), ('ocupado', 'Ocupado'), ('bloqueado', 'Bloqueado')], default='disponible', max_length=20)),
                ('reservado_hasta', models.DateTimeField(blank=True, null=True)),
                ('version', models.IntegerField(default=0)),
                ('asiento', models.ForeignKey(db_column='asiento_id', on_delete=django.db.models.deletion.PROTECT, related_name='funcion_asientos', to='showtimes.asiento')),
                ('funcion', models.ForeignKey(db_column='funcion_id', on_delete=django.db.models.deletion.CASCADE, related_name='funcion_asientos', to='showtimes.funcion')),
            ],
            options={
                'verbose_name': 'asiento de funcion',
                'verbose_name_plural': 'asientos de funcion',
                'db_table': 'funcion_asientos',
                'ordering': ['asiento__fila', 'asiento__numero'],
                'indexes': [models.Index(fields=['funcion'], name='idx_fa_funcion'), models.Index(fields=['funcion', 'estado'], name='idx_fa_funcion_estado')],
                'constraints': [models.UniqueConstraint(fields=('funcion', 'asiento'), name='uq_funcion_asiento')],
            },
        ),
        migrations.AddConstraint(
            model_name='sala',
            constraint=models.UniqueConstraint(fields=('cine', 'nombre'), name='uq_sala_cine_nombre'),
        ),
        migrations.AddIndex(
            model_name='funcion',
            index=models.Index(fields=['sala', 'fecha_hora_inicio'], name='idx_func_sala_horario'),
        ),
        migrations.AddIndex(
            model_name='funcion',
            index=models.Index(fields=['pelicula'], name='idx_func_pelicula'),
        ),
        migrations.AddConstraint(
            model_name='funcion',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_hora_fin__gt', models.F('fecha_hora_inicio'))), name='ck_funcion_rango_horario'),
        ),
        migrations.AddConstraint(
            model_name='funcion',
            constraint=models.CheckConstraint(condition=models.Q(('precio_base__gte', 0)), name='ck_funcion_precio_positivo'),
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('sala', 'fila', 'numero'), name='uq_asiento_sala_fila_numero'),
        ),
    ]
