# Generated by Django 5.1.6 on 2026-07-22 03:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'db_table': 'generos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('titulo_original', models.CharField(blank=True, max_length=200, null=True)),
                ('sinopsis', models.TextField(blank=True, null=True)),
                ('duracion_min', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('clasificacion', models.CharField(blank=True, max_length=10, null=True)),
                ('poster_url', models.CharField(blank=True, max_length=500, null=True)),
                ('backdrop_url', models.CharField(blank=True, max_length=500, null=True)),
                ('trailer_url', models.CharField(blank=True, max_length=500, null=True)),
                ('idioma_original', models.CharField(blank=True, max_length=50, null=True)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('reparto', models.CharField(blank=True, max_length=400, null=True)),
                ('calificacion', models.DecimalField(decimal_places=1, default=0, max_digits=3)),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pelicula',
                'verbose_name_plural': 'peliculas',
                'db_table': 'peliculas',
                'ordering': ['-fecha_estreno', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.CASCADE, to='movies.genero')),
                ('pelicula', models.ForeignKey(db_column='pelicula_id', on_delete=django.db.models.deletion.CASCADE, to='movies.pelicula')),
            ],
            options={
                'db_table': 'pelicula_generos',
            },
        ),
        migrations.AddField(
            model_name='pelicula',
            name='generos',
            field=models.ManyToManyField(related_name='peliculas', through='movies.PeliculaGenero', to='movies.genero'),
        ),
        migrations.AddConstraint(
            model_name='peliculagenero',
            constraint=models.UniqueConstraint(fields=('pelicula', 'genero'), name='uq_pelicula_genero'),
        ),
        migrations.AddIndex(
            model_name='pelicula',
            index=models.Index(fields=['activa'], name='idx_peliculas_activa'),
        ),
    ]
