# Generated by Django 5.1.6 on 2026-09-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='reparto_detalle',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
