# Generated by Django 5.1.6 on 2026-07-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta'), ('stripe', 'Stripe'), ('paypal', 'PayPal'), ('efectivo', 'Efectivo en taquilla')], default='tarjeta', max_length=30)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('transaccion_externa_id', models.CharField(blank=True, max_length=150, null=True)),
                ('tarjeta_ultimos4', models.CharField(blank=True, max_length=4, null=True)),
                ('mensaje', models.CharField(blank=True, max_length=200, null=True)),
                ('procesado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'pago',
                'verbose_name_plural': 'pagos',
                'db_table': 'pagos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_qr', models.CharField(max_length=255, unique=True)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ticket',
                'verbose_name_plural': 'tickets',
                'db_table': 'tickets',
                'ordering': ['-emitido_en'],
            },
        ),
    ]
