# Generated by Django 5.1.6 on 2026-07-22 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='reserva',
            field=models.ForeignKey(db_column='reserva_id', on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='reservations.reserva'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reserva',
            field=models.OneToOneField(db_column='reserva_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='reservations.reserva'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['idempotency_key'], name='idx_pagos_idempotency'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['reserva'], name='idx_pagos_reserva'),
        ),
    ]
